Repository AnkanSaha/AxioDB, pull requests merged in 2025-08, with the labels that each got.

#189 feat: add wrangler.toml configuration and update version to 2.21.70 i…
  Document/wrangler.toml
  package.json
Labels: size/M

#190 fix: correct syntax for pages_build_output_dir in wrangler.toml
  .github/workflows/Push.yml
  Document/wrangler.toml
Labels: size/M

#191 chore: update version to 2.21.71 in package.json
  package.json
Labels: size/XS

#192 fix: improve detection of changes in GUI and source folders in workflow
  .github/workflows/Push.yml
Labels: size/S

#196 Maintainer/ankan
  package.json
  source/Services/Aggregation/Aggregation.Operation.ts
  source/Services/CRUD Operation/Delete.operation.ts
  source/Services/CRUD Operation/Reader.operation.ts
  source/Services/CRUD Operation/Update.operation.ts
  source/engine/node/WorkerForDataLoad.engine.ts
  source/utility/BufferLoaderWithWorker.utils.ts
Labels: size/M

#197 docs: update class documentation for Database to clarify its purpose
  source/Services/Database/database.operation.ts
Labels: size/XS

#198 chore: update package versions and add Docker installation check
  package-lock.json
  package.json
  source/server/config/PortFreeChecker.ts
Labels: size/M

#199 refactor: remove check for GUI or source changes from workflow
  .github/workflows/Push.yml
Labels: size/M

#200 Maintainer/ankan
  GUI/src/components/dashboard/DatabaseTreeView.jsx
  GUI/src/components/dashboard/InMemoryCacheCard.jsx
  GUI/src/components/dashboard/StorageUsageCard.jsx
  GUI/src/components/dashboard/TotalCollectionsCard.jsx
  GUI/src/components/dashboard/TotalDatabasesCard.jsx
  GUI/src/components/dashboard/TotalDocumentsCard.jsx
  GUI/src/layout/Header.jsx
  GUI/src/pages/Dashboard.jsx
  package.json
  source/Services/Indexation.operation.ts
  source/caching/cache.operation.ts
  source/config/Interfaces/Operation/Indexation.operation.interface.ts
  source/server/config/PortFreeChecker.ts
  source/server/controller/Stats.controller.ts
  source/server/router/Router.ts
Labels: size/XL

#203 feat: add caching and transaction token support for collections and d…
  package.json
  source/server/controller/Collections/Collection.controller.ts
  source/server/controller/Database/Databse.controller.ts
  source/server/controller/Stats.controller.ts
  source/server/router/Routers/Collection.routes.ts
  source/server/router/Routers/DB.routes.ts
Labels: size/M

#204 fix: update version number and improve cache key format in Collection…
  package.json
  source/server/controller/Collections/Collection.controller.ts
Labels: size/XS

#205 fix: update version number in package.json and improve formatting in …
  package.json
Labels: size/XS

#207 feat: add API reference page and update routing; modify API paths to …
  GUI/src/config/config.jsx
  GUI/src/pages/ApiReference.jsx
  GUI/src/pages/Collections.jsx
  package.json
  source/server/config/keys.ts
Labels: size/XL

#208 Maintainer/ankan
  package.json
  source/server/controller/Collections/Collection.controller.ts
  source/server/controller/Database/Databse.controller.ts
Labels: size/S

#209 feat: update navigation path in Collections component and clear Globa…
  Docker/README.md
  GUI/src/pages/Collections.jsx
  package.json
  source/server/controller/Collections/Collection.controller.ts
  source/server/controller/Database/Databse.controller.ts
  source/server/controller/Operation/CRUD.controller.ts
Labels: size/L

#211 feat: update API endpoints for document operations to include by-id a…
  GUI/src/components/document/DeleteDocumentModal.jsx
  package.json
  source/server/config/keys.ts
  source/server/controller/Operation/CRUD.controller.ts
  source/server/router/Routers/Operation.routes.ts
Labels: size/L

#213 Maintainer/ankan
  Test/key.js
  Test/run.js
  package.json
  source/Services/Collection/collection.operation.ts
  source/server/config/keys.ts
  source/server/controller/Operation/CRUD.controller.ts
  source/server/router/Routers/Operation.routes.ts
Labels: size/L

#215 Maintainer/ankan
  .npmignore
  package-lock.json
  package.json
  source/server/config/keys.ts
Labels: size/S

#219 chore: update package versions to 2.30.90 and 2.30.89
  Document/src/components/content/Features.tsx
  README.md
  package-lock.json
  package.json
Labels: size/L

#220 Maintainer/ankan
  Docker/README.md
  README.md
  package.json
Labels: size/M

#221 Maintainer/ankan
  Scripts/versionController.sh
  package.json
Labels: size/M

#222 Maintainer/ankan
  GUI/src/config/config.jsx
  GUI/src/layout/Footer.jsx
  GUI/src/layout/Header.jsx
  GUI/src/pages/Status.jsx
  GUI/src/pages/Support.jsx
  Test/run.js
  package.json
  source/server/config/keys.ts
  source/server/router/Router.ts
Labels: size/XL

#224 Maintainer/ankan
  GUI/src/components/database/DatabaseList.jsx
  GUI/src/config/config.jsx
  GUI/src/layout/Footer.jsx
  GUI/src/layout/Header.jsx
  GUI/src/pages/Import.jsx
  GUI/src/pages/Status.jsx
  GUI/src/pages/Support.jsx
  Test/run.js
  package-lock.json
  package.json
  source/Services/Aggregation/Aggregation.Operation.ts
  source/Services/CRUD Operation/Create.operation.ts
  source/Services/CRUD Operation/Delete.operation.ts
  source/Services/CRUD Operation/Reader.operation.ts
  source/Services/CRUD Operation/Update.operation.ts
  source/Services/Indexation.operation.ts
  source/server/config/keys.ts
  source/server/controller/Database/Databse.controller.ts
  source/server/router/Router.ts
  source/server/router/Routers/DB.routes.ts
  source/utility/ZipUnzip.utils.ts
Labels: size/XXL

#225 refactor: remove GlobalStorage configuration and transaction token fr…
  package.json
  source/server/config/GlobalStorage.config.ts
  source/server/config/keys.ts
  source/server/controller/Collections/Collection.controller.ts
  source/server/controller/Database/Databse.controller.ts
  source/server/controller/Operation/CRUD.controller.ts
  source/server/controller/Stats.controller.ts
  source/server/router/Router.ts
  source/server/router/Routers/Collection.routes.ts
  source/server/router/Routers/DB.routes.ts
Labels: size/L

#226 Maintainer/ankan
  GUI/src/components/collection/CreateCollectionModal.jsx
  GUI/src/components/collection/DeleteCollectionModal.jsx
  GUI/src/components/database/CreateDatabaseModal.jsx
  GUI/src/components/database/DatabaseList.jsx
  GUI/src/components/database/DeleteDatabaseModal.jsx
  GUI/src/components/document/AggregateModal.jsx
  GUI/src/components/document/DeleteDocumentModal.jsx
  GUI/src/components/document/InsertDocumentModal.jsx
  GUI/src/components/document/UpdateDocumentModal.jsx
  GUI/src/config/config.jsx
  GUI/src/layout/Header.jsx
  GUI/src/pages/ApiReference.jsx
  GUI/src/pages/Collections.jsx
  GUI/src/pages/Dashboard.jsx
  GUI/src/pages/Databases.jsx
  GUI/src/pages/Documents.jsx
  GUI/src/pages/Import.jsx
  GUI/src/pages/Support.jsx
  GUI/src/store/store.js
  package.json
Labels: size/XXL

#227 fix: update version number to 2.31.96 in package.json and remove unus…
  package.json
  source/server/config/PortFreeChecker.ts
Labels: size/XS
